require '../lib/providers.rb'
require '../lib/devstack.rb'

IPS = {primary: '192.168.42.20',
       gw1: '192.168.42.21',
       gw2: '192.168.42.22',
       compute1: '192.168.42.23',
       compute2: '192.168.42.24',
       floating_gw1: '10.127.0.130',
       floating_gw2: '10.127.0.131',
       floating_compute1: '10.127.0.132',
       floating_compute2: '10.127.0.133'}

Vagrant.configure('2') do |config|

  config.ssh.forward_agent = true

  config.vm.define 'primary' do |primary|
    configure_providers(primary.vm, :ram => 6000, :vcpus=>2);
    primary.vm.network 'private_network', ip: IPS[:primary]
    primary.vm.hostname = 'primary'
    provision_devstack(primary,
                       local_conf: 'local.primary.conf',
                       local_sh: 'local.primary.sh',
                       env: IPS)
  end

  [:gw1, :gw2].each do |gw_n|
      config.vm.define "#{gw_n}" do |gw|
        configure_providers(gw.vm, :ram => 2000, :vcpus=>2);
        gw.vm.network 'private_network', ip: IPS[gw_]
        gw.vm.network 'private_network', ip: IPS["floating_#{gw_n}"]

        gw.vm.hostname = "#{gw_n}"
        provision_devstack(gw,
                           local_conf: 'local.gw.conf',
                           local_sh: 'local.gw.sh',
                           env: IPS)
      end
  end

  [:compute1, :compute2].each do |compute_n|
      config.vm.define "#{compute_n}" do |compute|
        configure_providers(compute.vm, :ram => 3000, :vcpus=>2);
        compute.vm.network 'private_network', ip: IPS[compute_n]
        compute.vm.network 'private_network', ip: IPS["floating_#{compute_n}"]

        compute.vm.hostname = "#{compute_n}"
        provision_devstack(compute,
                           local_conf: 'local.computenode.conf',
                           local_sh: 'local.computenode.sh',
                           env: IPS)
      end
  end
  

end
